language: node_js
cache:
  directories:
    - "~/.npm"
notifications:
  email:
    recipients:
      - guilherme.gois@gorilainvest.com.br
    on_success: change
    on_failure: always
node_js:
  - node
  - '6'
env:
  - NG_VERSION=4 TS_VERSION=2.3.4 MAT_VERSION=2.0.0-beta.12 CLI_VERSION=1.6.1 RX_VERSION=5.0.1
    RAMDA_VERSION=0.25.0 ZONEJS_VERSION=0.8.18
  - NG_VERSION=5 TS_VERSION=2.4.2 MAT_VERSION=5 CLI_VERSION=1.7.4 RX_VERSION=5.5.6 RAMDA_VERSION=0.25.0
    ZONEJS_VERSION=0.8.18
  - NG_VERSION=6 TS_VERSION=2.7.2 MAT_VERSION=6 CLI_VERSION=6 RX_VERSION=6 RAMDA_VERSION=0.25.0
    ZONEJS_VERSION=0.8.26
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g @angular/cli@${CLI_VERSION}
  - npm install rxjs@${RX_VERSION} ramda@${RAMDA_VERSION} typescript@${TS_VERSION} zone.js@${ZONEJS_VERSION}
  - npm install @angular/common@${NG_VERSION} @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}
  - npm install @angular/http@${NG_VERSION} @angular/platform-browser@${NG_VERSION}
    @angular/platform-browser-dynamic@${NG_VERSION}
  - npm install @angular/compiler@${NG_VERSION} @angular/compiler-cli@${NG_VERSION}
  - npm install @angular/animations@${NG_VERSION} @angular/cdk@${MAT_VERSION} @angular/material@${MAT_VERSION}
  - npm install
script:
  - npm run build
  - npm run test:once
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
